### ISSUE TITLE
Information regarding sentencepiece and the tokenizer+numericalizer.

### ISSUE THREAD

**Issue by ankitvad** [mmcux/de-nds-translation#3]
Hi, I've been checking your code for: translation_sentencepiece.py  
https://github.com/mmcux/de-nds-translation/blob/4c8b3ffb0cc7439e0ce583c767de1dd68d67d552/translation_sentencepiece.py#L165

Here, you use the sentencepiece library to create the model then load it using the torchtext function - load_sp_model and then for 
`tokenize = sp_model.encode` acts as the tokenizer and numericalizer like the transformer library.. I'm assuming a similar example which comes from here: https://github.com/pytorch/text/issues/609  
for the transformer library.

I've been trying with the latest version of torchtext and sentencepiece and torch but it keeps mentioning: 
```
SRC = Field(use_vocab = False, tokenize = sp_de.encode,
AttributeError: __torch__.torch.classes.torchtext.SentencePiece does not have a field with name 'encode'
```
Can you tell me the version of the library that it works with?

**Comment by mmcux** [comment]
Hi @ankitvad ,

as mentioned in the other issue it is probably a better idea to work without the Field class. As a quick workaround you could try it with the following versions as it works for me on Windows 10 and Ubuntu 20.04 :
```
pytorch==1.5.0
sentencepiece==0.1.91
torchtext==0.6.0
```
Maybe it helps! And sorry for the messy code, I am working on it ;-)

Another way for you could be to load your sentencepiece model into a tokenizer from the transformers library, for example the [T5-Tokenizer](https://huggingface.co/transformers/model_doc/t5.html#t5tokenizer) where you can use the prepare_seq2seq_batch method. Then load it into a pytorch dataset and iterator and you could continue with your code as before.

**Comment by ankitvad** [comment]
Yeah, that makes sense. I'm not sure how to move away from the usage of Field class and the effect it will have on the other dependencies. With the Iterator and TabularDataset class. Do you have any experience with this?  

Anyways, thanks a lot for providing the library version. Stuff seems to work for me now :)) A quick hack. But atleast it works! (Y)

**Comment by mmcux** [comment]
Glad it works now!

Unfortunately I don't have experience with the TabularDataset.
Is your goal to train a new translation algorithm with a custom tokenizer? Right now I am switching to the transformers library, take a similar model to my language pairs and "retrain" it with my data. Works well so far.
